stages:
  - build
  - test
  - deploy


before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-job:
  stage: build
  script:
    - cd auth
    - ./gradlew bootJar
  only:
    - master


deploy-job:
  stage: deploy
  script:
    - cd build\libs
    - java -jar .\auth-0.0.1-SNAPSHOT.jar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week


test-job:
  stage: test
  script:
    - echo "hello"

after_script:
  - echo "End CI"

