stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-job:
  stage: build
  script:
    - gradlew auth:bootJar
  only:
    - master

test-job:
  stage: test
  script:
    - gradlew auth:test
  only:
    - master

after_script:
  - echo "End CI"

