stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-job:
  stage: build
  script:
    - cd auth
    - ./gradlew auth:bootJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test-job:
  stage: test
  script:
    - ./gradlew auth:test
  only:
    - master

after_script:
  - echo "End CI"

