stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-job:
  stage: build
  script:
    - cd auth
    - ./gradlew bootJar
    - cd build\libs
    - java -jar .\auth-0.0.1-SNAPSHOT.jar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test-job:
  stage: test
  script:
    - echo "hello"
  only:
    - master

after_script:
  - echo "End CI"

