stages:
  - build
  - test
  - docker-build

before_script:
  - docker info
  - export GRADLE_USER_HOME=`pwd`/.gradle

build-auth:
  stage: build
  script:
    - ./gradlew auth:bootJar
    - ls -l auth/build/libs/
  artifacts:
    paths:
      - auth/build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test-auth:
  stage: test
  script:
    - ./gradlew auth:test
    - ls -l test/build/libs/
  needs:
    - build-auth
  only:
    - master

build-chat:
  stage: build
  script:
    - ./gradlew chat:bootJar
    - ls -l chat/build/libs/
  artifacts:
    paths:
      - chat/build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test-chat:
  stage: test
  script:
    - ./gradlew chat:test
  needs:
    - build-chat
  only:
    - master

build-facade:
  stage: build
  script:
    - ./gradlew facade:bootJar
    - ls -l facade/build/libs/
  artifacts:
    paths:
      - facade/build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test-facade:
  stage: test
  script:
    - ./gradlew facade:test
  needs:
    - build-facade
  only:
    - master

build-mediafiles:
  stage: build
  script:
    - ./gradlew mediafiles:bootJar
    - ls -l mediafiles/build/libs/
  artifacts:
    paths:
      - mediafiles/build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test-mediafiles:
  stage: test
  script:
    - ./gradlew mediafiles:test
  needs:
    - build-mediafiles
  only:
    - master

docker-build-auth:
  stage: docker-build
  script:
    - cd auth
    - ls
    - docker build -t kirillshakhov/auth-service:$CI_COMMIT_REF_NAME .
    - docker push kirillshakhov/auth-service:$CI_COMMIT_REF_NAME
  only:
    - master
  dependencies:
    - test-auth

docker-build-chat:
  stage: docker-build
  script:
    - cd chat
    - ls
    - docker build -t kirillshakhov/chat-service:$CI_COMMIT_REF_NAME .
    - docker push kirillshakhov/chat-service:$CI_COMMIT_REF_NAME
  only:
    - master
  dependencies:
    - test-chat

docker-build-facade:
  stage: docker-build
  script:
    - cd facade
    - ls
    - docker build -t kirillshakhov/facade-service:$CI_COMMIT_REF_NAME .
    - docker push kirillshakhov/facade-service:$CI_COMMIT_REF_NAME
  only:
    - master
  dependencies:
    - test-facade

docker-build-mediafiles:
  stage: docker-build
  script:
    - cd mediafiles
    - ls
    - docker build -t kirillshakhov/mediafiles-service:$CI_COMMIT_REF_NAME .
    - docker push kirillshakhov/mediafiles-service:$CI_COMMIT_REF_NAME
  only:
    - master
  dependencies:
    - test-mediafiles

after_script:
  - echo "End CI"
