version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    image: mongo
  eureka-service:
    hostname: eureka-service
    build:
      context: ./eureka
    container_name: eureka-service
    networks:
      net:
        aliases:
          - eureka-service
  auth-service:
    hostname: auth-service
    build:
      context: ./auth
    container_name: auth-service
    depends_on:
      - eureka-service
      - mongo
    networks:
      net:
        aliases:
          - auth-service
    ports:
      - '9992:9992'

networks:
  net:
    driver: bridge